# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: FrontDeskAgent
version: "1.2.0"
slug: frontdeskagent
description: FrontDeskAgent add-on
url: "https://github.com/ion-g-ion/FrontDeskAgent/tree/main/frontdeskagent"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/ion-g-ion/{arch}-addon-frontdeskagent"
